services:

  web:
    build: .
    container_name: crm_web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DB_NAME: crmdb
      DB_USER: root
      DB_PASSWORD: root123
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: crm_db
    environment:
      MYSQL_DATABASE: crmdb
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: crm_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
